import Link from "next/link";
import Image from "next/image";
import CommentsSection from "../../../components/CommentSection";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const posts: Record<string, { title: string; content: string; image: string }> = {
  1: { 
    title: "Tropical Beach Paradise",
    content: "Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post1c.png" 
  },
  2: { 
    title: "Emerald Valley", 
    content:"Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post2.png"
  },
  3: { 
    title: "The Golden Desert",
    content: "Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post3.png"
  },

  4: { 
    title: "MyStic Mountain",
    content:"Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post4.png"
  },
  5: { 
    title: "The Crystal Clear Lake",
    content:"Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post5.png"
  },
  6: { 
    title: "Island Of Dream",
    content:"Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip." ,
    image: "/post6.png"
  },
  7: { 
    title: "Lost Lagoon",
    content: "Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post7.png"
  },
  8: { 
    title: "Frozen Paradise",
    content:"Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post8.png"
  },
  9: { 
    title: "Whispering Woods",
    content: "Traveling is a remarkable journey that goes beyond the simple act of moving from one destination to another; it is a transformative experience that expands horizons and creates lasting memories. Each journey is an adventure filled with unique opportunities to explore, learn, and grow as an individual. The world is vast and diverse, offering endless wonders to discover, from towering mountains that kiss the sky to serene beaches where waves gently caress the shore. It is not just about the places we visit but also about the experiences that shape us along the way. Each destination holds its own distinct charm, history, and culture, allowing us to step into a world that feels entirely different from what we know.The magic of traveling lies in the connections we form, not just with the places we visit but also with the people we meet. Every interaction, whether with a local sharing stories of their homeland or a fellow traveler embarking on a similar path, adds depth to our journey. These connections remind us of our shared humanity, despite the diversity of traditions, languages, and lifestyles that define our world. Wandering through bustling marketplaces filled with vibrant colors, tantalizing aromas, and the chatter of locals offers a sensory experience that brings us closer to the heart of a culture. Tasting local cuisines, prepared with love and rooted in history, opens a window into the essence of a place, telling stories that words often cannot convey.Traveling also pushes us out of our comfort zones, encouraging us to embrace challenges and uncertainties. It teaches resilience and adaptability as we navigate unfamiliar terrains, try to communicate in new languages, and solve unexpected problems. These moments of uncertainty often turn into the most cherished stories, filled with laughter and lessons. A delayed flight or a missed connection might lead to unexpected detours that reveal hidden gems—a quaint village, an untouched trail, or a kind stranger offering help. These unplanned adventures often turn out to be the most memorable highlights of a trip.",
    image: "/post9.png"
  }
};

type PostProps = {
  params: { id: string };
};

export async function generateStaticParams() {
  return Object.keys(posts).map((id) => ({ id }));
}

export default function Post({ params }: PostProps) {
  const post = posts[params.id as string];

  if (!post) return <div>Post not found</div>;

  return (
    <div>
      <Navbar />
      <div className="max-w-4xl mx-auto p-4 sm:p-6">
        <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold mb-4 text-center">{post.title}</h1>

        <div className="flex justify-center">
          <Image
          width={500}
          height={300}
            src={post.image}
            alt={post.title}
            className="mt-2 w-full max-w-[800px] h-60 object-cover rounded"
          />
        </div>

        <p className="text-base sm:text-lg lg:text-xl text-gray-800 mt-4 leading-relaxed">
          {post.content}
        </p>

        <div >
          <Link href="/" passHref>
            <button className="mt-6 bg-blue-600 text-white  px-4 py-2 sm:px-6 sm:py-3 rounded hover:bg-blue-400 transition duration-200">
              Back to Home
            </button>
          </Link>
        </div>
      

        <CommentsSection />
      </div>
      <Footer />
    </div>
    
  );
}